import pandas as pd
from pathlib import Path

from sqlalchemy import create_engine
from etl.db_config import load_db_config
from etl.logger import logging, timed, section


# Path to the CSV file generated by the extract step
CSV_PATH = "data/job_listings/job_listings_all.csv"
TRANSFORM_PATH = "data/job_listings/job_listings_transformed.csv"


def path_to_transformed_csv():
    if not Path(TRANSFORM_PATH).parent.exists():
        Path(TRANSFORM_PATH).parent.mkdir(parents=True, exist_ok=True)
    return TRANSFORM_PATH


def load_data():
    df = pd.read_csv(CSV_PATH)
    return df


def transform_data(df):

    # normalize column names
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

    # Convert date_posted to datetime format
    df['date_posted'] = pd.to_datetime(
        df['date_posted'], errors='coerce')

    # Extract the city from the location column
    df['city'] = df['location'].apply(
        lambda x: x.split(',')[0].strip() if pd.notnull(x) else None)

    return df


def extract_experience_level(df):

    def get_experience_level(title):
        title = title.lower()
        if 'senior' in title:
            return 'Senior'
        elif 'junior' in title:
            return 'Junior'
        elif 'lead' in title:
            return 'Lead'
        elif 'principal' in title:
            return 'Principal'
        elif 'manager' in title:
            return 'Manager'
        elif 'head' in title:
            return 'Head'
        else:
            return 'Entry-Level'
    # Feature engineering: Extract experience level from job title
    df['experience_level'] = df['title'].apply(get_experience_level)

    # Reorder columns
    df = df[["title", "experience_level", "company",
             "location", "city", "date_posted", "salary", "link", "job_type"]]

    return df


def save_to_csv(df, filename):
    filename = path_to_transformed_csv()
    df.to_csv(filename, index=False)
    logging.info(f"Data saved to {filename}")


def load_to_postgres(df):
    engine = create_engine(load_db_config())
    df.to_sql('job_listings', engine, if_exists='replace', index=False)
    logging.info("Data loaded to PostgreSQL database successfully.")


@timed
def main():
    section("Loading Data")
    df = load_data()
    logging.info(f"Loaded {len(df)} records from {CSV_PATH}")

    section("Transforming Data")
    df = transform_data(df)
    df = extract_experience_level(df)
    logging.info(
        f"\033[92m🎉 Data transformation complete. Sample data:\033[0m")
    logging.info(df.head())

    section("Saving Transformed Data")
    transformed_csv_path = path_to_transformed_csv()
    save_to_csv(df, transformed_csv_path)
    logging.info(
        f"\033[92m🎉 Transformed data saved to {transformed_csv_path}\033[0m")

    section("Loading Transformed Data to PostgreSQL")
    load_to_postgres(df)
    logging.info(f"\033[92m🎉 Data loaded to PostgreSQL successfully.\033[0m")


if __name__ == "__main__":
    main()
